Category.create(name: "College")
Category.create(name: "Work")
Category.create(name: "Travel")
Category.create(name: "DIY")
Category.create(name: "Finance")
Category.create(name: "Sports")
Category.create(name: "Fitness")
Category.create(name: "Health")
